FROM ruby:3.3-slim

WORKDIR /app

# Install build dependencies and PostgreSQL client
RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y \
    build-essential libpq-dev libyaml-dev postgresql-client && \
    rm -rf /var/lib/apt/lists/*

# Install gems
COPY Gemfile Gemfile.lock ./
RUN bundle install

# Copy app code
COPY . .

# Expose Rails default port
EXPOSE 3000

# Entrypoint: prepare DB then start server
# CMD bash -c "bin/rails db:prepare && bin/rails server -b 0.0.0.0 -p 3000"
CMD bash -c "rm -f tmp/pids/server.pid && bin/rails db:prepare && bin/rails server -b 0.0.0.0 -p 3000"