version: "3.9"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bash -c "rails db:create db:migrate && rails server -b 0.0.0.0"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  db_data: